@testable import StolenBike///
/// @Generated by Mockolo
///



import Combine
import Foundation


class LocationManagerMock: LocationManager {
    init() { }

     typealias OnGetLocation = (Result<Location, Error>) -> Void

    private(set) var getLocationCallCount = 0
    var getLocationHandler: ((@escaping OnGetLocation) -> ())?
    func getLocation(onGetLocation: @escaping OnGetLocation)  {
        getLocationCallCount += 1
        if let getLocationHandler = getLocationHandler {
            getLocationHandler(onGetLocation)
        }
        
    }
}

class LocationRepositoryMock: LocationRepository {
    init() { }


    private(set) var readCallCount = 0
    var readHandler: (() -> (AnyPublisher<Location, Error>))?
    func read() -> AnyPublisher<Location, Error> {
        readCallCount += 1
        if let readHandler = readHandler {
            return readHandler()
        }
        fatalError("readHandler returns can't have a default value thus its handler must be set")
    }
}

