name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      xcode_simulator: 'platform=iOS Simulator,name=iPhone 13 Pro,OS=16.2'
      xcode_project: app/StolenBike.xcodeproj
      xcode_scheme: StolenBike
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Tests
      run: xcodebuild test -scheme ${xcode_scheme} -project ${xcode_project} -destination "${xcode_simulator}" -resultBundlePath TestResults | xcpretty --color
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
