name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: app/StolenBike.xcodeproj
        scheme: StolenBike
        destination: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
        action: test
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
