name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      xcodebuild_test: xcodebuild test -project app/StolenBike.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: AppFeatureTests
      run: $xcodebuild_test -scheme AppFeatureTests | xcpretty
    - name: BikeFeatureTests
      run: $xcodebuild_test -scheme BikeFeatureTests | xcpretty
      
#    - name: Swift Coverage Conversion
#      run: tools/generate_lcov.sh
#    - name: Codecov
#      uses: codecov/codecov-action@v3.1.0
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
