name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      xcode_simulator: 'platform=iOS Simulator,name=iPhone 13 Pro,OS=16.2'
      xcode_project: app/StolenBike.xcodeproj
      xcode_scheme: StolenBike
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: app/StolenBike.xcodeproj
        scheme: StolenBike
        destination: 'platform=iOS Simulator,name=iPhone 13 Pro,OS=16.2'
        action: test
        result-bundle-path: TestResults.xcresult
    - name: Test result
      uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
