name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      xcode_simulator: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
      xcode_project: app/StolenBike.xcodeproj
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: AppFeatureTests
      run: xcodebuild test -scheme AppFeatureTests -project ${xcode_project} -destination "${xcode_simulator}" | xcpretty
    - name: BikeFeatureTests
      run: xcodebuild test -scheme BikeMapFeatureTests -project ${xcode_project} -destination "${xcode_simulator}" | xcpretty
      
#    - name: Swift Coverage Conversion
#      run: tools/generate_lcov.sh
#    - name: Codecov
#      uses: codecov/codecov-action@v3.1.0
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
