name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    env:
      xcode_simulator: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
      xcode_project: app/StolenBike.xcodeproj
      xcode_scheme: StolenBike
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: ${xcode_project}
        scheme: ${xcode_scheme}
        destination: ${xcode_simulator}
        action: test
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
